In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as mse
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_percentage_error as mape

In [2]:
DF = pd.read_csv(r'City_MedianRentalPrice_AllHomes.csv')

In [3]:
DF

Unnamed: 0       RegionName State  \
0              0         New York    NY   
1              1      Los Angeles    CA   
2              2          Houston    TX   
3              3          Chicago    IL   
4              4      San Antonio    TX   
...          ...              ...   ...   
1694        1694  Hillsboro Beach    FL   
1695        1695       Amagansett    NY   
1696        1696           Quogue    NY   
1697        1697            Ogden    KS   
1698        1698        Wainscott    NY   

                                      Metro          CountyName  SizeRank  \
0               New York-Newark-Jersey City       Queens County         1   
1            Los Angeles-Long Beach-Anaheim  Los Angeles County         2   
2          Houston-The Woodlands-Sugar Land       Harris County         3   
3                  Chicago-Naperville-Elgin         Cook County         4   
4                 San Antonio-New Braunfels        Bexar County         5   
...                                     ...                 ...       ...   
1694  Miami-Fort Lauderdale-West Palm Beach      Broward County      1695   
1695            New York-Newark-Jersey City      Suffolk County      1696   
1696            New York-Newark-Jersey City      Suffolk County      1697   
1697                              Manhattan        Riley County      1698   
1698            New York-Newark-Jersey City      Suffolk County      1699   

      2010-01  2010-02  2010-03  2010-04  ...  2019-03  2019-04  2019-05  \
0         NaN      NaN      NaN      NaN  ...   2800.0   2875.0   2900.0   
1         NaN      NaN      NaN      NaN  ...   3500.0   3500.0   3500.0   
2         NaN      NaN      NaN      NaN  ...   1500.0   1544.0   1550.0   
3         NaN   1600.0   1500.0   1500.0  ...   1775.0   1795.0   1800.0   
4         NaN      NaN      NaN      NaN  ...   1300.0   1300.0   1325.0   
...       ...      ...      ...      ...  ...      ...      ...      ...   
1694      NaN      NaN      NaN      NaN  ...   2700.0   2650.0   2737.5   
1695      NaN      NaN      NaN      NaN  ...  30000.0  33333.0  36000.0   
1696      NaN      NaN      NaN      NaN  ...  30000.0  30000.0  30000.0   
1697      NaN      NaN      NaN      NaN  ...    990.0    990.0    990.0   
1698      NaN      NaN      NaN      NaN  ...  40000.0  34750.0  35000.0   

      2019-06  2019-07  2019-08  2019-09  2019-10  2019-11  2019-12  
0      2895.0   2850.0   2925.0   2900.0   2900.0   2899.0   2900.0  
1      3520.0   3500.0   3600.0   3607.0   3665.0   3600.0   3550.0  
2      1550.0   1550.0   1550.0   1550.0   1500.0   1500.0   1500.0  
3      1800.0   1800.0   1812.5   1800.0   1800.0   1766.0   1750.0  
4      1345.0   1349.0   1322.5   1299.0   1300.0   1299.0   1300.0  
...       ...      ...      ...      ...      ...      ...      ...  
1694   2775.0   3000.0   3000.0   3150.0   3000.0   3150.0   3395.0  
1695  36333.0  35000.0  30000.0  30000.0  34000.0  33041.5  35000.0  
1696  30000.0  30000.0  29500.0  30000.0  30000.0  30000.0  31666.0  
1697    990.0    909.0    939.0    909.0    909.0    939.0    909.0  
1698  35000.0  35000.0  30000.0  30000.0  28333.0  25000.0  28333.0  

[1699 rows x 126 columns]

In [4]:
DF.columns.to_numpy()

array(['Unnamed: 0', 'RegionName', 'State', 'Metro', 'CountyName',
       'SizeRank', '2010-01', '2010-02', '2010-03', '2010-04', '2010-05',
       '2010-06', '2010-07', '2010-08', '2010-09', '2010-10', '2010-11',
       '2010-12', '2011-01', '2011-02', '2011-03', '2011-04', '2011-05',
       '2011-06', '2011-07', '2011-08', '2011-09', '2011-10', '2011-11',
       '2011-12', '2012-01', '2012-02', '2012-03', '2012-04', '2012-05',
       '2012-06', '2012-07', '2012-08', '2012-09', '2012-10', '2012-11',
       '2012-12', '2013-01', '2013-02', '2013-03', '2013-04', '2013-05',
       '2013-06', '2013-07', '2013-08', '2013-09', '2013-10', '2013-11',
       '2013-12', '2014-01', '2014-02', '2014-03', '2014-04', '2014-05',
       '2014-06', '2014-07', '2014-08', '2014-09', '2014-10', '2014-11',
       '2014-12', '2015-01', '2015-02', '2015-03', '2015-04', '2015-05',
       '2015-06', '2015-07', '2015-08', '2015-09', '2015-10', '2015-11',
       '2015-12', '2016-01', '2016-02', '2016-03', '2016

In [5]:
DF.isnull().sum().to_numpy()

array([   0,    0,    0,    1,    0,    0, 1698, 1669, 1637, 1619, 1616,
       1615, 1609, 1600, 1579, 1564, 1549, 1533, 1415, 1320, 1299, 1288,
       1263, 1229, 1198, 1173, 1157, 1135, 1125, 1116, 1104, 1098, 1088,
       1076, 1070, 1062, 1055, 1047, 1043, 1036, 1030, 1024, 1016, 1009,
       1005,  998,  994,  982,  968,  966,  961,  950,  940,  939,  934,
        927,  922,  920,  920,  911,  904,  897,  893,  887,  885,  883,
        881,  880,  879,  875,  873,  872,  871,  868,  864,  863,  862,
        861,  861,  859,  857,  855,  854,  836,  818,  801,  792,  768,
        743,  683,  444,  364,  324,  308,  284,  267,  255,  242,  232,
        227,  213,  201,  183,  175,  156,  145,  115,   95,   79,   65,
         53,   43,   34,   18,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0], dtype=int64)

In [6]:
DF.index

RangeIndex(start=0, stop=1699, step=1)

In [7]:
DF_Filt = DF.iloc[:,-16:-1]
DF_Filt #Contains all numerical we want
for x in DF_Filt.columns.to_numpy():
   sc = StandardScaler()
   DF_Filt[x] = sc.fit_transform(DF_Filt[x].values.reshape(-1,1))
  
DFLblColumns = DF.iloc[:,1:6]
print(DFLblColumns.columns)
for x in DFLblColumns.columns.to_numpy():
   le = LabelEncoder() 
   DF_Filt[x] = le.fit_transform(DFLblColumns[x].values)


Index(['RegionName', 'State', 'Metro', 'CountyName', 'SizeRank'], dtype='object')


In [8]:
DF_Filt

2018-09    2018-10    2018-11    2018-12    2019-01    2019-02  \
0      0.621298   0.563252   0.533636   0.473809   0.402008   0.435649   
1      1.040543   0.988258   0.990069   0.862050   0.719991   0.778566   
2     -0.196079  -0.206894  -0.208069  -0.199143  -0.188533  -0.201196   
3     -0.042255  -0.038603  -0.054023  -0.069729  -0.074967  -0.090973   
4     -0.350506  -0.329547  -0.325030  -0.305263  -0.281656  -0.301621   
...         ...        ...        ...        ...        ...        ...   
1694        NaN        NaN        NaN        NaN   0.447434   0.533626   
1695  18.175297  18.904136  18.905095  17.142313  15.029235  13.760411   
1696        NaN        NaN        NaN  14.554036  13.893581  13.760411   
1697  -0.555001  -0.497838  -0.459678  -0.427429  -0.388862  -0.421642   
1698        NaN        NaN        NaN        NaN  19.571852  18.659221   

        2019-03    2019-04    2019-05    2019-06    2019-07    2019-08  \
0      0.430212   0.455801   0.440898   0.440647   0.436403   0.515446   
1      0.773593   0.760724   0.721742   0.735661   0.755059   0.871677   
2     -0.207497  -0.193562  -0.191001  -0.194221  -0.200909  -0.210211   
3     -0.072597  -0.071105  -0.073983  -0.076215  -0.078349  -0.071676   
4     -0.305606  -0.312604  -0.296318  -0.290985  -0.299448  -0.330274   
...         ...        ...        ...        ...        ...        ...   
1694   0.381157   0.346029   0.364836   0.384005   0.509939   0.555027   
1695  13.773045  15.315535  15.934133  16.224081  16.197630  14.804280   
1696  13.773045  13.689444  13.125692  13.234773  13.746429  14.540405   
1697  -0.457675  -0.463845  -0.453123  -0.458552  -0.515153  -0.532666   
1698  18.678499  16.006856  15.466060  15.594877  16.197630  14.804280   

        2019-09    2019-10    2019-11  RegionName  State  Metro  CountyName  \
0      0.523207   0.500260   0.538715         941     34    216         365   
1      0.907593   0.896405   0.925779         787      4    181         258   
2     -0.210769  -0.224710  -0.233758         614     43    139         181   
3     -0.074847  -0.069359  -0.086883         229     14     59          97   
4     -0.347234  -0.328277  -0.344742        1221     43    272          32   
...         ...        ...        ...         ...    ...    ...         ...   
1694   0.659129   0.552044   0.677307         594      9    196          45   
1695  15.257094  16.604953  17.182209          25     34    216         440   
1696  15.257094  14.533610  15.502813        1129     34    216         440   
1697  -0.559271  -0.530751  -0.543520        1002     16    190         373   
1698  15.257094  13.670378  12.742011        1453     34    216         440   

      SizeRank  
0            0  
1            1  
2            2  
3            3  
4            4  
...        ...  
1694      1681  
1695      1682  
1696      1683  
1697      1684  
1698      1685  

[1699 rows x 20 columns]

In [9]:
Y = DF.iloc[:,-1]
scY = StandardScaler()
Y = scY.fit_transform(Y.values.reshape(-1,1))
Y

array([[ 0.51476613],
       [ 0.85969586],
       [-0.22815946],
       ...,
       [15.77976423],
       [-0.54178018],
       [14.01107068]])

In [10]:
X = DF_Filt
X

2018-09    2018-10    2018-11    2018-12    2019-01    2019-02  \
0      0.621298   0.563252   0.533636   0.473809   0.402008   0.435649   
1      1.040543   0.988258   0.990069   0.862050   0.719991   0.778566   
2     -0.196079  -0.206894  -0.208069  -0.199143  -0.188533  -0.201196   
3     -0.042255  -0.038603  -0.054023  -0.069729  -0.074967  -0.090973   
4     -0.350506  -0.329547  -0.325030  -0.305263  -0.281656  -0.301621   
...         ...        ...        ...        ...        ...        ...   
1694        NaN        NaN        NaN        NaN   0.447434   0.533626   
1695  18.175297  18.904136  18.905095  17.142313  15.029235  13.760411   
1696        NaN        NaN        NaN  14.554036  13.893581  13.760411   
1697  -0.555001  -0.497838  -0.459678  -0.427429  -0.388862  -0.421642   
1698        NaN        NaN        NaN        NaN  19.571852  18.659221   

        2019-03    2019-04    2019-05    2019-06    2019-07    2019-08  \
0      0.430212   0.455801   0.440898   0.440647   0.436403   0.515446   
1      0.773593   0.760724   0.721742   0.735661   0.755059   0.871677   
2     -0.207497  -0.193562  -0.191001  -0.194221  -0.200909  -0.210211   
3     -0.072597  -0.071105  -0.073983  -0.076215  -0.078349  -0.071676   
4     -0.305606  -0.312604  -0.296318  -0.290985  -0.299448  -0.330274   
...         ...        ...        ...        ...        ...        ...   
1694   0.381157   0.346029   0.364836   0.384005   0.509939   0.555027   
1695  13.773045  15.315535  15.934133  16.224081  16.197630  14.804280   
1696  13.773045  13.689444  13.125692  13.234773  13.746429  14.540405   
1697  -0.457675  -0.463845  -0.453123  -0.458552  -0.515153  -0.532666   
1698  18.678499  16.006856  15.466060  15.594877  16.197630  14.804280   

        2019-09    2019-10    2019-11  RegionName  State  Metro  CountyName  \
0      0.523207   0.500260   0.538715         941     34    216         365   
1      0.907593   0.896405   0.925779         787      4    181         258   
2     -0.210769  -0.224710  -0.233758         614     43    139         181   
3     -0.074847  -0.069359  -0.086883         229     14     59          97   
4     -0.347234  -0.328277  -0.344742        1221     43    272          32   
...         ...        ...        ...         ...    ...    ...         ...   
1694   0.659129   0.552044   0.677307         594      9    196          45   
1695  15.257094  16.604953  17.182209          25     34    216         440   
1696  15.257094  14.533610  15.502813        1129     34    216         440   
1697  -0.559271  -0.530751  -0.543520        1002     16    190         373   
1698  15.257094  13.670378  12.742011        1453     34    216         440   

      SizeRank  
0            0  
1            1  
2            2  
3            3  
4            4  
...        ...  
1694      1681  
1695      1682  
1696      1683  
1697      1684  
1698      1685  

[1699 rows x 20 columns]

In [11]:
print(X.isnull().sum())
for col in X:
    X.fillna(X[col].median(),inplace=True)
    #X = X.fillna(X[col].median())
print(X.isnull().sum())

2018-09       53
2018-10       43
2018-11       34
2018-12       18
2019-01        0
2019-02        0
2019-03        0
2019-04        0
2019-05        0
2019-06        0
2019-07        0
2019-08        0
2019-09        0
2019-10        0
2019-11        0
RegionName     0
State          0
Metro          0
CountyName     0
SizeRank       0
dtype: int64
2018-09       0
2018-10       0
2018-11       0
2018-12       0
2019-01       0
2019-02       0
2019-03       0
2019-04       0
2019-05       0
2019-06       0
2019-07       0
2019-08       0
2019-09       0
2019-10       0
2019-11       0
RegionName    0
State         0
Metro         0
CountyName    0
SizeRank      0
dtype: int64


In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=60)

In [13]:
model = LinearRegression()
#model = Pipeline([('poly', PolynomialFeatures(degree=3)),('linear', LinearRegression(fit_intercept=False))])
hist = model.fit(X_train,Y_train)

In [19]:
Y_pred = model.predict(X_test)
#Ypred

In [20]:
#Y_test

In [21]:
Y_pred = scY.inverse_transform(Y_pred)
Y_test = scY.inverse_transform(Y_test)

In [22]:
err = mse(Y_pred,Y_test,squared=False)
print(err)

4761405.044537444


In [23]:
print(Y_test.mean())

3578553.3175121825


In [25]:
err2 = mape(Y_pred,Y_test)
print(err2)

1885.0869917231485


In [29]:
import numpy as np

M = np.random.rand(3,4)


In [35]:
M

array([[0.341892  , 0.22642685, 0.40373637, 0.64179767],
       [0.90701194, 0.32688975, 0.8875375 , 0.62441697],
       [0.67592849, 0.33496845, 0.62218727, 0.21407213]])